app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

BlogBundle_list:
    path:      /{page}
    defaults:  { _controller: BlogBundle:Blog:list, page: 1 }
    requirements:
        page:  \d+

BlogBundle_profile:
    path:      /user/{username}/{page}
    defaults:  { _controller: BlogBundle:Blog:user, page: 1}
    requirements:
        page:  \d+

BlogBundle_show:
    path:      /article/{id}
    defaults:  { _controller: BlogBundle:Article:show }
    requirements:
        id:  \d+

BlogBundle_new:
    path:      /new
    defaults:  { _controller: BlogBundle:Article:new }

BlogBundle_create:
    path:      /create
    defaults:  { _controller: BlogBundle:Article:create }
    requirements:
        methods:  POST

BlogBundle_comment_create:
    path:     /comment/{id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        methods:  POST
        id: \d+

API_article:
    path:      /api/article/{id}
    defaults:  { _controller: AppBundle:Api/BlogApi:article}
    requirements:
        id:  \d+
        type: (0|1|-1)

API_article_create:
    path:      /api/article/new
    defaults:  { _controller: AppBundle:Api/BlogApi:createArticle}
    requirements:
        methods:  POST

API_comment:
    path:      /api/comment/{id}
    defaults:  { _controller: AppBundle:Api/BlogApi:comment}
    requirements:
        id:  \d+
        type: (0|1|-1)

API_comment_create:
    path:      /api/comment/{id}/new
    defaults:  { _controller: AppBundle:Api/BlogApi:createComment}
    requirements:
        id:  \d+
        methods:  POST