app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
BlogBundle_list:
    path:      /blog/{page}
    defaults:  { _controller: BlogBundle:Blog:list, page: 1 }
    requirements:
        page:  \d+

BlogBundle_show:
    path:      /blog/article/{id}
    defaults:  { _controller: BlogBundle:Blog:show }
    requirements:
        id:  \d+

BlogBundle_new:
    path:      /blog/new
    defaults:  { _controller: BlogBundle:Blog:new }
    requirements:
        methods:  POST

BlogBundle_comment_create:
    path:     /comment/{id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        methods:  POST
        id: \d+

API_article:
    path:      /api/article/{id}
    defaults:  { _controller: AppBundle:Api/BlogApi:article}
    requirements:
        id:  \d+
        type: (0|1|-1)

API_comment:
    path:      /api/comment/{id}
    defaults:  { _controller: AppBundle:Api/BlogApi:comment}
    requirements:
        id:  \d+
        type: (0|1|-1)
