app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
BlogBundle_list:
    path:      /blog/{page}
    defaults:  { _controller: BlogBundle:Blog:list, page: 1 }
    requirements:
        page:  \d+

BlogBundle_show:
    path:      /blog/article/{id}
    defaults:  { _controller: BlogBundle:Blog:show }
    requirements:
        id:  \d+

BlogBundle_like:
    path:      /blog/article/{id}/like
    defaults:  { _controller: BlogBundle:Api:article, type: 1}
    requirements:
        id:  \d+

BlogBundle_dislike:
    path:      /blog/article/{id}/dislike
    defaults:  { _controller: BlogBundle:Api:article, type: -1}
    requirements:
        id:  \d+

BlogBundle_new:
    path:      /blog/new/
    defaults:  { _controller: BlogBundle:Blog:new }