<?php

namespace BlogBundle\Repository;

/**
 * ArticleFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
