<?php

namespace BlogBundle\Repository;

/**
 * ArticleTextsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTextsRepository extends \Doctrine\ORM\EntityRepository
{
}
