<?php

namespace BlogBundle\Repository;


use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    function findOneWithUserLike($id, $userId)
    {
        $qb = $this->createQueryBuilder('a')
            ->select(['a', 'l', 't', 'f', 'c', 'cl'])
            ->where('a.id=:id')
            ->leftJoin('a.likes', 'l', 'WITH', 'l.userId=:userId')
            ->leftJoin('a.contentTexts', 't')
            ->leftJoin('a.contentFiles', 'f')
            ->leftJoin('a.comments', 'c')
            ->leftJoin('c.likes', 'cl')
            ->setParameters(['id'=>$id, 'userId' => $userId]);

        $res = $qb->getQuery()
            ->getOneOrNullResult();

        return $res;
    }
}
