<?php

namespace BlogBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    function findWithUserLike($id, $userId)
    {
        $qb = $this->createQueryBuilder('c')
            ->addSelect('l')
            ->where('c.articleId=:id')
            ->leftJoin('c.likes', 'l', 'WITH', 'l.userId=:userId')
            ->setParameters(['id'=>$id, 'userId' => $userId]);

        $res = $qb->getQuery()
            ->getResult();

        return $res;
    }
}
