<?php

namespace BlogBundle\Repository;

/**
 * CommentsLikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsLikesRepository extends \Doctrine\ORM\EntityRepository
{
}
